name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Compress files
        run: |
          cd ./packages/cli
          zip bpm-${{ steps.get_version.outputs.VERSION }}.zip ./bpm
      - name: Release archives
        uses: softprops/action-gh-release@v1
        with:
          files: ./bpm-${{ steps.get_version.outputs.VERSION }}.zip
