name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        uses: olegtarasov/get-tag@v2.1
        id: get_version
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Compress files
        run: |
          cp ./packages/cli/bin/bpm .
          zip bpm-${{ steps.get_version.outputs.tag }}.zip ./bpm
      - name: Release archives
        uses: softprops/action-gh-release@v1
        with:
          files: ./bpm-${{ steps.get_version.outputs.tag }}.zip
