name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create_image:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Release archives
        uses: softprops/action-gh-release@v1
        with:
          files: ./packages/cli/bpm
